### ISSUE TITLE
misc suggestions

### ISSUE THREAD

**Issue by cranmer** [kratsg/ATLASstylempl#1]
Nice! I’d suggest adding an example or two in the readme. Maybe even a comparison to an equivalent ROOT based plot.

Might also consider adding this to scikit-hep.

**Comment by matthewfeickert** [comment]
> Might also consider adding this to scikit-hep.

I think that anyone reading this by now knows, but for the person who doesn't and stumbles across this, this was mostly added into [`mplhep`](https://github.com/scikit-hep/mplhep) back [in this early commit](https://github.com/scikit-hep/mplhep/commit/0ecfa8d65d567b19cd6ae7972001ec640aa4a0c6) by @andrzejnovak (it is now under [`styles_atlas.py`](https://github.com/scikit-hep/mplhep/blob/447ab2fefd7c3b1dedd5f0b9dd3e9fa80fa6685c/mplhep/styles_atlas.py)). So you can now just do

```python
import matplotlib.pyplot as plt
import mplhep as hep
plt.style.use(hep.style.ATLAS)
```

@kratsg Not sure if this is good enough to close the Issue, or if you want to add a link advertising this to the `README`.
